apiVersion: v1
kind: Service
metadata: 
  name: seasonapp
spec:
  type: ClusterIP
  selector:
    app: seasonapp 
  ports:
    - port: 8080
      targetPort: 8080
      name: tomcat
      protocol: TCP