apiVersion: v1
kind: Service
metadata: 
  name: studentapp
spec:
  type: ClusterIP
  selector:
    app: studentapp 
  ports:
    - port: 8080
      targetPort: 8080
      name: tomcat
      protocol: TCP